<?xml version="1.0"?>
<robot name="furiguide_diff_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find furiguide_description)/urdf/materials.xacro" />

<!-- Properties (MKS) -->
<xacro:property name="M_PI" value="3.1415926535897931"/>
<xacro:property name="base_height" value="0.02" />
<xacro:property name="base_radius" value="0.15" />
<xacro:property name="base_mass" value="5" />

<xacro:property name="caster_height" value="0.08" />
<xacro:property name="caster_radius" value="0.025" />
<xacro:property name="caster_mass" value="0.5" />

<xacro:property name="wheel_mass" value="0.25" />
<xacro:property name="wheel_height" value="0.04" />
<xacro:property name="wheel_radius" value="0.08" />
<xacro:property name="wheel_separation" value="0.4" />

<xacro:property name="base_x_origin_to_wheel_origin" value="0.25" />
<xacro:property name="base_y_origin_to_wheel_origin" value="0.3" />
<xacro:property name="base_z_origin_to_wheel_origin" value="0.0" />

<!-- Cylinder Inertia Macro (source: Kaustav5422) -->
<xacro:macro name="cylinder_inertia" params="m r h">
  <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
            iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
            izz="${m*r*r/2}" /> 
</xacro:macro>

<!-- Caster -->
<xacro:macro name="caster" params="fb translateX:=0 translateY:=0">
  <collision name='${fb}_caster_collision'>
    <origin xyz="${translateX} 0 -0.05" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
    <surface>
      <friction>
        <ode>
          <mu>0</mu>
          <mu2>0</mu2>
          <slip1>1.0</slip1>
          <slip2>1.0</slip2>
        </ode>
      </friction>
    </surface>
  </collision>

  <visual name='${fb}_caster_visual'>
    <origin xyz="${translateX} 0 -0.05" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
  </visual>
</xacro:macro>

<link name='chassis'>
  <pose>0 0 0.1 0 0 0</pose>
  
  <inertial>
    <mass value="${base_mass}"/>
    <origin xyz="0.0 0 0.1" rpy="0 0 0"/>
    <inertia
      ixx="0.1" ixy="0" ixz="0"
      iyy="0.1" iyz="0"
      izz="0.1"
    />
  </inertial>

  <collision name='collision'>
    <geometry>
      <cylinder length="${base_height}" radius="${base_radius}"/>
    </geometry>
  </collision>

  <visual name='chassis_visual'>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${base_height}" radius="${base_radius}"/>
    </geometry>
  </visual>

  <caster fb="front" translateX="-0.15" />
  <caster fb="rear" translateX="0.15" />

</link>

<!-- Wheels -->
<xacro:macro name="wheel" params="lr parent translateX:=0.0 translateY:=0.0">
  <link name="${lr}_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" />
      <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />

    </inertial>

    <collision name="${lr}_wheel_collision">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
      <material name="Maroon" />
    </visual>
  </link>

  <gazebo reference="${lr}_wheel">
    <mu1 value="1.0" />
    <mu2 value="1.0" />
    <kp value="10000000.0" />
    <kd value="1.0" />
    <fdir1 value="1 0 0" />
    <material>Gazebo/Red</material>
  </gazebo>


  <joint type="continuous" name="${lr}_wheel_axle">
    <child link="${lr}_wheel" />
    <origin xyz="${translateX * base_x_origin_to_wheel_origin} 
                 ${translateY * base_y_origin_to_wheel_origin}
                 ${base_z_origin_to_wheel_origin}"
            rpy="0 0 0" />

    <parent link="${parent}" />
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="100" velocity="100" />
    <joint_properties damping="1.0" friction="1.0" />
  </joint>
</xacro:macro>

<wheel lr="left" parent="chassis" translateY="0.5"/>
<wheel lr="right" parent="chassis" translateY="-0.5"/>

<!-- Gazebo Specific Configuration -->
<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <legacyMode>false</legacyMode>
    <alwaysOn>true</alwaysOn>
    <updateRate>10</updateRate>
    <leftJoint>left_wheel_axle</leftJoint>
    <rightJoint>right_wheel_axle</rightJoint>
    <wheelSeparation>${wheel_separation}</wheelSeparation>
    <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
    <torque>10</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>chassis</robotBaseFrame>
  </plugin>
</gazebo>

<gazebo reference="chassis">
  <material>Gazebo/Orange</material>
</gazebo>

</robot>
